spring:
  application:
    name: personal-finance-tracker
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    jwt:
      secret: 9837HD32H87WIDTHS873HD387HDKOJABAS9IUH3G
      expiration: 86400000 # 24 hours
  mail:
    host: smtp.gmail.com
    port: 587
    username: ali.salimov.2006@gmail.com
    password: as051312
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    org.springframework.security: DEBUG
    com.financetracker: DEBUG
